league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        enable_password_grant: true
        enable_implicit_grant: true
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available: ['email', 'profile']
        default: ['email']
    persistence:
        doctrine: null
    client:
        allow_plaintext_secrets: false

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
